### ISSUE TITLE
RGH unconditionally overrides GitHub-set custom tab size

### ISSUE THREAD

**Issue by auscompgeek** [sindresorhus/refined-github#1244]
In various scenarios, GitHub will change the tab-size:
* [GitHub respects .editorconfig](https://github.com/RReverser/github-editorconfig#readme) when viewing blobs and diffs.
* A user can [append ts=2](https://github.com/tiimgreen/github-cheat-sheet#adjust-tab-space), for example, to the query string to force viewing a blob/diff with that tab size.

There is currently no (easy) way to tell Refined GitHub to respect the tab size set by GitHub.

**Comment by sindresorhus** [comment]
You can override it with the "Custom CSS" option.

**Comment by auscompgeek** [comment]
That's not a very elegant solution. You'd need to paste this brittle monstrosity in; note the additional universal selector:
```css
.tab-size[data-tab-size="1"] * {
	-moz-tab-size: 1 !important;
	tab-size: 1 !important;
}
.tab-size[data-tab-size="2"] * {
	-moz-tab-size: 2 !important;
	tab-size: 2 !important;
}
.tab-size[data-tab-size="3"] * {
	-moz-tab-size: 3 !important;
	tab-size: 3 !important;
}
.tab-size[data-tab-size="4"] * {
	-moz-tab-size: 4 !important;
	tab-size: 4 !important;
}
.tab-size[data-tab-size="5"] * {
	-moz-tab-size: 5 !important;
	tab-size: 5 !important;
}
.tab-size[data-tab-size="6"] * {
	-moz-tab-size: 6 !important;
	tab-size: 6 !important;
}
.tab-size[data-tab-size="7"] * {
	-moz-tab-size: 7 !important;
	tab-size: 7 !important;
}
.tab-size[data-tab-size="8"] * {
	-moz-tab-size: 8 !important;
	tab-size: 8 !important;
}
.tab-size[data-tab-size="9"] * {
	-moz-tab-size: 9 !important;
	tab-size: 9 !important;
}
.tab-size[data-tab-size="10"] * {
	-moz-tab-size: 10 !important;
	tab-size: 10 !important;
}
.tab-size[data-tab-size="11"] * {
	-moz-tab-size: 11 !important;
	tab-size: 11 !important;
}
.tab-size[data-tab-size="12"] * {
	-moz-tab-size: 12 !important;
	tab-size: 12 !important;
}
```
