### ISSUE TITLE
add an option to show the repos you contribute to

### ISSUE THREAD

**Issue by Thatkookooguy** [sindresorhus/refined-github#1248]
I wanted to use this extension, but it hides some things I use on a regular basis and can't seem to find an option to add back

for example, I use the "repos you contribute to" section pretty frequently to quickly navigate to repos I don't own.

is there a way to add that back with the current settings?

thanks

**Comment by yakov116** [comment]
@Thatkookooguy github created a great tool for that!! The best is you don't even need an extention!

Its called...... The search tool.
Search the repo and you will see that you can add your own custom CSS to add it back

**Comment by bfred-it** [comment]
In the options, paste this CSS:

```css
.dashboard-sidebar > .boxed-group[role="navigation"] {
	display: block !important;
}
```
