### ISSUE TITLE
Repositories tabs

### ISSUE THREAD

**Issue by 1138-4EB** [sindresorhus/refined-github#1370]
Prior to the last update to the main dashboard by GitHub, the 'Repositories' section in the sidebar (previously on the right, now on the left) was divided in several tabs by refined-github: all, forked, own... I really miss that feature.

**Comment by 1138-4EB** [comment]
The view now is equivalent to the 'All' filter, isn't it? I mean that implementing the feature back would not affect the current usability.

However, going to your profile is not as usable, because each entry takes 5 lines of text (with a larger font size). Is it possible to visualize the filtered list in your profile with each entry taking a single line? That would allow to see at least 15 repos without scrolling.

**Comment by bfred-it** [comment]
> visualize the filtered list in your profile with each entry taking a single line

You can do this with this piece of CSS code, but we can't make it the default:

```css
#user-repositories-list > ul > li *{
	display: inline !important;
}
#user-repositories-list > ul > li > div:nth-child(n+3) {
	display: none !important;
}
```

<img width="745" alt="" src="https://user-images.githubusercontent.com/1402241/41294507-7cb445a6-6e58-11e8-84e7-a31b513b2273.png">


> the 'Repositories' section in the sidebar was divided in several tabs by refined-github

It was not done by Refined GitHub. Honestly I never used it, I only need the recent tabs and for anything else I just visit it from the browser history or the new search field.
