### ISSUE TITLE
Add opt-in setting to remove diff signs

### ISSUE THREAD

**Issue by jerone** [sindresorhus/refined-github#1464]
There is (or [was](https://github.com/sindresorhus/refined-github/pull/1451)) a feature called [`remove-diff-signs.js`](https://github.com/sindresorhus/refined-github/blob/master/source/features/remove-diff-signs.js), but it's [intention](https://github.com/sindresorhus/refined-github/pull/1451#issuecomment-409374499) is to make the diff signs unselectable. Personally I think those signs are redundant in combination with the background colors in the diffs and can be removed.

If this feature request is approved, then the following code is probably all you need to include:
```css
.blob-code-marker-addition:before,
.blob-code-marker-context:before,
.blob-code-marker-deletion:before {
	display: none !important;
}
```
