### ISSUE TITLE
Way to view code blocks with loooong lines better

### ISSUE THREAD

**Issue by janpio** [sindresorhus/refined-github#1515]
Code blocks with long lines (as they appear in stack traces and similar) are shown with a scroll bar on Github:

```
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
```

That, combined with the 700px width of the comments makes it very hard to get an overview of the actual content.

![image](https://user-images.githubusercontent.com/183673/45153448-4db9b780-b1d4-11e8-99ba-a0007b9bfb20.png)

It would be awesome if something like a "fullscreen" button would appear in the top right of the code block that e.g. takes the code block out of the comment box and lets it use the full screen width. 

Bad mockup:
![image](https://user-images.githubusercontent.com/183673/45153409-25ca5400-b1d4-11e8-9e16-8b1c1f604d9e.png)
(Uses `width:1800px; position:relative; left:-480px;` to simulate the effect)

Maybe this could also be dynamic so it just uses the size it needs to the lines be fully displayed.

If the total screen width still is not enough, it would still show the scrollbar of course.

**Comment by janpio** [comment]
For log files and stack traces this would unfortunately make them much harder to read and understand.

**Comment by sindresorhus** [comment]
Thanks for sharing the example. Makes sense.

I agree this could be useful. It should only be as wide as not needing a scrollbar anymore.

**Comment by sindresorhus** [comment]
Wonder if we could solve this with a gesture instead. Like press and hold to make it pop out, then click outside to close it. Open to ideas.

**Comment by janpio** [comment]
I personally would also prefer an icon button, similar to the "Edit readme" button for example, positioned in the top right corner of the pre/code.

**Comment by Mottie** [comment]
In [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark) we use the following global css:

```css
body:not(.nowrap) .blob-code-inner,
body:not(.nowrap) .markdown-body pre > code,
body:not(.nowrap) .markdown-body .highlight > pre {
  white-space: pre-wrap !important;
  word-break: break-all !important;
  overflow-wrap: break-word !important;
  display: block !important;
}
body:not(.nowrap) td.blob-code-inner {
  display: table-cell !important;
}
```

You can toggle a class of "nowrap" on the body to toggle the feature.

There is also a [GitHub toggle code wrap userscript](https://greasyfork.org/en/scripts/18789-github-toggle-code-wrap) that adds a button within each code block to allow toggling of the line wrap.
