### ISSUE TITLE
Distinct referenced commits style

### ISSUE THREAD

**Issue by sompylasar** [sindresorhus/refined-github#1579]
### Before

<img width="786" alt="before" src="https://user-images.githubusercontent.com/498274/46896325-533c9a00-ce31-11e8-948d-c9be7a479cf7.png">

### Before (with explanation of the problem)

Confusing, looks like the pull request commits and the commit that references this pull request are in the same branch.

<img width="786" alt="before-explanation" src="https://user-images.githubusercontent.com/498274/46896331-58014e00-ce31-11e8-9571-b59762f33a9b.png">

### After

<img width="786" alt="after" src="https://user-images.githubusercontent.com/498274/46896352-76674980-ce31-11e8-81c9-c309c5d3fb8b.png">

### Style

```css
.discussion-item-header[id^=ref-] .discussion-item-icon {
  background-color: #6db2ff;
  color: #ffffff;
}

.discussion-item-header[id^=ref-]::before {
  content: '';
  position: absolute;
  display: block;
  z-index: -1;
  left: -25px;
  top: -40px;
  width: 2px;
  height: 140px;
  background-color: #ffffff;
}

.discussion-item-header[id^=ref-commit-] + .discussion-item-body .timeline-commits .commit .commit-icon {
  color: #6db2ff;
}

.discussion-item-header {
  position: relative;
}

.discussion-item-header[id^=ref-commit-]::after {
  content: '';
  position: absolute;
  display: block;
  z-index: 0;
  left: -25px;
  top: 30px;
  bottom: -20px;
  width: 2px;
  background-color: #6db2ff;
}

.discussion-item-header[id^=ref-commit-] + .discussion-item-body .timeline-commits {
  position: relative;
}
```

https://gist.github.com/sompylasar/99b5d307da3168b833c1119fb95caf11
