### ISSUE TITLE
Reactions container stretches beyond width of comment area

### ISSUE THREAD

**Issue by Daniel15** [sindresorhus/refined-github#1744]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2430%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/refined-github/issues/1744)

The new "eyeballs" and "spaceship" reactions are making the container too wide

![](https://d.sb/2019/01/firefox_24-12.05.36.png)

See how it overlaps the right column.

PR in the screenshot: https://github.com/facebook/react/pull/14679

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $30.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($30.00)
### Submitted pull Requests
- [#2416 Wrap reactions-avatars](https://issuehunt.io/r/sindresorhus/refined-github/pull/2416)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/refined-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by bfred-it** [comment]
`if types > 4, return`

We can't add any avatars in that case, unless we stop at 1/2 avatars, which would look kinda wonky

<img width="710" alt="screenshot 2019-01-27 at 21 12 01" src="https://user-images.githubusercontent.com/1402241/51802862-40cb5c80-2278-11e9-8d84-8ec188ab8007.png">

**Comment by jerone** [comment]
What about some flexbox...
![image](https://user-images.githubusercontent.com/55841/51805933-e6300180-2273-11e9-9d63-68de559f2be0.png)

```css
.comment-reactions-options {
    flex-wrap: wrap;
    justify-content: stretch;
    margin-bottom: -1px;
}
.reaction-summary-item {
    border-bottom: 1px solid #d1d5da;
    flex: 1 1 auto;
}
```
