### ISSUE TITLE
Why you hide count field for "Watch" and "Fork" buttons?

### ISSUE THREAD

**Issue by kvolkovich-sc** [sindresorhus/refined-github#1843]
**GitHub**

![github-original](https://user-images.githubusercontent.com/24652543/54083007-12d53f80-432f-11e9-8fa8-3b2ee3cce7f8.png)

**GitHub refined**

![github-refined](https://user-images.githubusercontent.com/24652543/54082988-ec170900-432e-11e9-95aa-7f57c487cb14.png)

---

I personally prefer original variant.

If you don't want to fix it, maybe you have a CSS snippet to got it back?

**Comment by mxmilkb** [comment]
This now makes it three clicks instead of two to get to a projects Network page.

More > Insights > Network

(Previously the number linked to the network page, so it was just one click, but GitHub changed this a couple of years ago IIRC)

**Comment by kvolkovich-sc** [comment]
Adding to **Custom CSS** field in extension settings solve this issue: 

```
.social-count[href$='/network/members'],
.social-count[href$='/watchers'] {
	display: initial;
}
```

**Comment by mxmilkb** [comment]
Ah, thank you, silly of me to miss that.

**Comment by jerone** [comment]
[**@kvolkovich-sc**](https://github.com/kvolkovich-sc) commented on [Mar 10, 2019, 2:22 PM GMT+1](https://github.com/sindresorhus/refined-github/issues/1843#issuecomment-471301974 "2019-03-10T13:22:50Z - Replied by Github Reply Comments"):
> Adding to **Custom CSS** field in extension settings solve this issue:
> 
> ```
> .social-count[href$='/network/members'],
> .social-count[href$='/watchers'] {
> 	display: initial;
> }
> ```

Your CSS wasn't enough for me to show the counters again. This is:
```css
a.btn-with-count[title^='Fork your own'],
[action='/notifications/subscribe'] a.btn-with-count {
  border-radius: initial;
}
a.social-count[href$='/network/members'],
a.social-count[href$='/watchers'] {
	display: initial;
}
```
