### ISSUE TITLE
Star/Unstar from Dashboard

### ISSUE THREAD

**Issue by jaymickey** [sindresorhus/refined-github#1864]
Without Refined GitHub installed users are able to star/unstar repos from the dashboard homepage based on the activity of those you follow. With Refined GitHub installed this feature disappears. It might be nice to add it back in? 

## Before
![image](https://user-images.githubusercontent.com/7720995/54559766-af937f00-49b8-11e9-8e74-9535531bc6dd.png)

## After
![image](https://user-images.githubusercontent.com/7720995/54559494-18c6c280-49b8-11e9-9432-629c77066e95.png)

Thanks for your time!

**Comment by bfred-it** [comment]
It’s a feature. You can restore them via some CSS

**Comment by MostHated** [comment]
I have added this to the CSS portion under preferences of the Addon but they have not shown back up, unfortunately. Has the method to redisplay them changed since this was posted?

**Comment by fregante** [comment]
@MostHated yes it has, `.dashboard .watch_started .border-gray.flex-items-baseline .text-bold.text-gray-dark` now contains both the title and the star button, and we're hiding them together:

```css

/* #1864 restore Star/Unstar buttons in dashboard */
.dashboard .flex-items-baseline [value='Star'],
.dashboard .flex-items-baseline [value='Unstar'] {
	display: block;
}
.dashboard .watch_started .border-gray.flex-items-baseline .text-bold.text-gray-dark  {
	display: block !important;
}
```
