### ISSUE TITLE
How can I custom the background color?

### ISSUE THREAD

**Issue by nasyxx** [sindresorhus/refined-github#1868]
Hello, I found a recent update to conflict with one of my extensions, but I couldn't find where the background color css is.

<img width="303" alt="Screen Shot 2019-03-21 at 11 53 29 AM" src="https://user-images.githubusercontent.com/5007613/54732846-0e334580-4bd1-11e9-92b3-7e3738322945.png">

I have tried to add this to the custom css, but still no reaction.
```css
html.gr__github_com.refined-github:root{
  --github-gray-background: #333!important;
  background-color: #333!important;
}
}
div.body{
  background-color: #333!important;
}
```

Can you please give me some tips?
