### ISSUE TITLE
Conflict with Dark Reader on the dashboard news feed

### ISSUE THREAD

**Issue by spikespaz** [sindresorhus/refined-github#1899]
There's a pretty annoying conflict with the popular Dark Reader extension.

![image](https://user-images.githubusercontent.com/12502988/55313632-1e42f480-541d-11e9-82c2-0b84f3bd8eeb.png)

The dashboard news feed is completely white. While not the fault of this extension, I couldn't find the feature that turns this change on or off. I tried disabling all of the features, but the issue persisted.

If the feature isn't in the `features/` folder, how could I disable it until the issue with Dark Reader is resolved? I consider both of these extensions mandatory.

https://github.com/darkreader/darkreader/issues/1195

**Comment by bfred-it** [comment]
Not a bug. You can find the relevant selector and apply some CSS in there. 

I find it weird that an extension expects to darken _the entire web_ without conflicts. At least try GitHub Dark

**Comment by mikhaelkh** [comment]
You have an injected stylesheet for that section that's messing with Dark Reader's:
```css
.dashboard .js-all-activity-header + div {
    background-color: rgb(255, 255, 255);
    margin-top: 8px !important;
    border-width: 1px;
    border-style: solid;
    border-color: rgb(209, 213, 218);
    border-image: initial;
    border-radius: 3px;
}
```
So yes, this extension is responsible for this behavior too.
What do you mean by "GitHub Dark"? [This](https://chrome.google.com/webstore/detail/github-dark-theme/odkdlljoangmamjilkamahebpkgpeacp)? It suffers from that stylesheet too.
