### ISSUE TITLE
Upload message showing in comment box

### ISSUE THREAD

**Issue by doms** [sindresorhus/refined-github#1992]
Not sure if it's just me, but the upload message is now showing in the comment box rather than being hidden like one would expect here:

```css
.rgh-has-upload-field .is-default .drag-and-drop {
    display: none;
}
```

<img width="776" alt="Screen_Shot_2019-04-27_at_11_32_33_PM" src="https://user-images.githubusercontent.com/8808097/56858746-1b1c2500-6945-11e9-829b-0a3bc340f465.png">

It looks to me that the rule is being ignored (tested on both Chromium and Firefox)

<img width="829" alt="Screen Shot 2019-04-27 at 11 06 12 PM" src="https://user-images.githubusercontent.com/8808097/56858751-3850f380-6945-11e9-9516-4da29ea656c2.png">

Adding `important!` does solve the issue, but wasn't sure if that was the preferred solution.. But if it is, I can quickly make the change.

**Comment by bfred-it** [comment]
Yeah the `!important` is required now because they have a utility class on it:

```css
.d-flex {
    display: flex !important;
}
```
