### ISSUE TITLE
Drop `upload-button` feature

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#2014]
The feature is currently broken. It was initially added because we hide this bar via CSS:

<img width="403" alt="" src="https://user-images.githubusercontent.com/1402241/57218510-108a1b80-7028-11e9-8fb2-a07066175553.png">

However now we have two reasons why this is not useful:

- `upload-button` now also takes care of hiding the bar; i.e. the feature can be disabled altogether and the bar reappears
- we now also offer a CSS field to restore the bar

Additionally:

- We have a related feature that [drops the Upload files button from file lists](https://github.com/sindresorhus/refined-github/blob/master/source/features/remove-upload-files-button.tsx) and does not add an alternative. Likewise, people can just upload files via drag-drop or disable the feature.

Therefore we can either:

- 👎 Keep the feature as JS, but **not** add the alternative button
- 👍 Drop the JS feature and just hide the bar via CSS (who doesn't want it can undo it easily in the custom CSS field)

**Comment by Mange** [comment]
> who doesn't want it can undo it easily in the custom CSS field

How can I undo this? I cannot use drag-and-drop so I need to be able to click this button to get a file selector up and it's not clear to me what I can do to get it back.

**Comment by bfred-it** [comment]
Probably 

```css
.drag-and-drop {
	display: block !important;
}
```

**Comment by Mange** [comment]
I finally got it working with

```css
/* Restore upload message on comment box */
body file-attachment.is-default .drag-and-drop {
	display: flex !important;
}
```

I had to add `body` to add extra specificity since the stylesheet overrides in the settings are loaded before the stylesheet, so it didn't win the specificity war.

![Screenshot showing stylesheet order in Firefox](https://user-images.githubusercontent.com/1599/58727281-27801b80-83e4-11e9-974e-c05a54fef270.png)

**Comment by bfred-it** [comment]
`!important` doesn’t care about specificity, the last important wins 😅

**Comment by Mange** [comment]
I'm pretty sure it still counts, it's just that it's sorted "important,
specificity". So important always wins over non-important, but among
important the specificity still wins.

I'm not sure how else the trick would have fixed it.

Den lör 1 juni 2019 04:52Federico Brigante <notifications@github.com> skrev:

**Comment by Mange** [comment]
An update for any future searchonauts:

Since #2086, you need to use this override in the CSS:

```css
/* Restore upload message on comment box */
body file-attachment.js-upload-markdown-image.is-default .drag-and-drop {
	display: flex !important;
}
```
