### ISSUE TITLE
Vertically align the asset download counts in releases

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#2126]
https://github.com/electron/electron/releases

Vertically align them on the icon. And with some more right margin. Would make it look cleaner. I think we could use CSS grid for this.

<img width="982" alt="Screen Shot 2019-06-07 at 12 00 36" src="https://user-images.githubusercontent.com/170270/59091214-10d44a00-8939-11e9-94f1-3c37727603b8.png">

**Comment by sindresorhus** [comment]
// @dotconnor

**Comment by jerone** [comment]
+1 And also put count and filesize in different columns.

**Comment by dotconnor** [comment]
Could someone in the right direction for using css grid? From my understanding css grid only has parent-child relationships, and the given layout is:

```html
<container>
	<row>
		<item>
	</row>
	<row>
		<item>
	</row>
</container>
```

**Comment by dotconnor** [comment]
@jerone Still need the downloads to be left aligned, something you can only do with a table/grid. (I think?)

**Comment by jerone** [comment]
[**@dotconnor**](https://github.com/dotconnor) commented on [Jun 8, 2019, 12:18 PM GMT+2](https://github.com/sindresorhus/refined-github/issues/2126#issuecomment-500113036 "2019-06-08T10:18:42Z - Replied by Github Reply Comments"):
> [@jerone](https://github.com/jerone) Still need the downloads to be left aligned, something you can only do with a table/grid. (I think?)

Don't think left align the downloads makes it visually better;

![image](https://user-images.githubusercontent.com/55841/59145791-f2c62280-89e8-11e9-9610-8cbabcce4b8a.png)

```less
.py-1 small {
    min-width: 60px;
    display: inline-block;

    &:nth-child(2) {
        text-align: right;
    }
}
```

**Comment by dotconnor** [comment]
![image](https://user-images.githubusercontent.com/14323370/59145946-cdb9bb80-89b8-11e9-9032-a2235f759000.png)

```css
.release .Box-body small:nth-child(2) {
	min-width: 60px;
	display: inline-block;
	text-align: right;
}
```
and flex aligning the children
