### ISSUE TITLE
Tooltips are broken in files when `indented-code-wrapping` is enabled

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#2305]
https://github.com/sindresorhus/refined-github/pull/2293/files#diff-041820b02ac3d6d7c4e862285d60afb5L62

![image](https://user-images.githubusercontent.com/16872793/62499748-c55fe000-b7b1-11e9-9f47-bb1db84a1798.png)

**Comment by fregante** [comment]
Needs:

```css
.tooltipped::after {
	text-indent: initial;
}
```
