### ISSUE TITLE
Readd URL format

### ISSUE THREAD

**Issue by ShalokShalom** [sindresorhus/refined-github#2311]
Hi :hugs: 

I looked into the settings, while I was unable to find any option to restore the URL formating (that one which you use to first mark a certain text and then press it, so it becomes [text]() automatically.

**Comment by fregante** [comment]
I don't know what feature you're talking about, is it `shorten-links`?

**Comment by ShalokShalom** [comment]
Nope. Its up there in the editing field. Normally.

**Comment by fregante** [comment]
Ah I see. The buttons that have shortcuts have been hidden from that bar. You can press the shortcuts or restore the buttons by undoing the CSS. I think the feature is called “clean rich text editor”

**Comment by ShalokShalom** [comment]
Ah, and is there no trigger to set?

**Comment by jerone** [comment]
There is indeed no feature called `clean-rich-text-editor` in the settings, only a [CSS file](https://github.com/sindresorhus/refined-github/blob/master/source/features/clean-rich-text-editor.css).

This is how I solved it:

```css
/* Show comment toolbar items */
:root md-mention,
:root md-ref,
:root markdown-toolbar > :nth-last-child(4) { /* H1, B, I */
	display: inline-block !important;
}
```
