### ISSUE TITLE
Big input box on issue page, for search box

### ISSUE THREAD

**Issue by garyking** [sindresorhus/refined-github#2435]
Screenshot attached, for Refined GitHub disabled and enabled. The search box is huge on issues pages.

Refined GitHub disabled:

![1 - Refined GitHub - Disabled](https://user-images.githubusercontent.com/343940/64807784-f4613280-d563-11e9-83e1-c26ca900ec1a.png)

Refined GitHub enabled:

![2 - Refined GitHub - Enabled](https://user-images.githubusercontent.com/343940/64807807-fcb96d80-d563-11e9-9db4-67df293a4111.png)

**Comment by pdonias** [comment]
(Pull requests page as well)

**Comment by rfc1459** [comment]
The error boils down to the rules in [source/features/widen-search-field.css@6cc38da#L1-L10](https://github.com/sindresorhus/refined-github/blob/6cc38da/source/features/widen-search-field.css#L1-L10) which were added 5 months ago, so this might be caused by a CSS change on GitHub's end.

Quick and dirty workaround (which disables the automatic expansion of the search field, though):
```css
.subnav,
.subnav-search,
.subnav-search-input,
.subnav [role='search'],
.page-content .subnav > .float-right { /* Global search field container */
	flex-grow: unset !important;
	display: unset !important;
}
```

A proper fix is far beyond my CSS skillset :-)
