### ISSUE TITLE
Change button colour background to the `Draft` PR label

### ISSUE THREAD

**Issue by ntwb** [sindresorhus/refined-github#2450]
It's nice to have "labels" on our pull requests, though with a `Draft` pull request this isn't always practical, though when you view a list of PRs the `Draft` PR label/status is easily missed, adding a light grey background colour to the `Draft` text would help make these stand out a little clearer IMHO.

Example URL: https://github.com/WordPress/gutenberg/pulls
![Screen Shot 2019-09-20 at 12 47 58 pm](https://user-images.githubusercontent.com/1016458/65295506-e97e5180-dba4-11e9-9e6c-c9aa339e7615.png)

**Comment by fregante** [comment]
<img width="136" alt="Screenshot 2019-09-20 at 10 31 05" src="https://user-images.githubusercontent.com/1402241/65297380-c9916280-db91-11e9-8d03-5125cf9f4437.png">


Like this?

```css
/* demo */
span[aria-label="Open draft pull request"] {
    background: #e8e8e8 !important;
    width: 1.6em;
    display: inline-flex;
    height: 1.6em;
    align-items: center;
    justify-content: center;
    border-radius: 50%;
    margin: -1em;
    margin-left: -0.4em;
    margin-right: -0.2em;
}
span[aria-label="Open draft pull request"] svg {
	color: white !important;
}
```
