### ISSUE TITLE
Show anchor link symbols next to headlines only on hover

### ISSUE THREAD

**Issue by tooomm** [sindresorhus/refined-github#2453]
I realized that recently the anchor links always show next to the headline.
They used to only highlight/show up when you hover... I liked that way more!

Example URL: https://github.com/sindresorhus/refined-github/blob/master/readme.md

**Comment by fregante** [comment]
I don't understand, are you talking about [comments-time-machine-links](https://github.com/sindresorhus/refined-github/blob/b1fe47a4c16d1165b6d4628a682bdeac8413ba5d/source/features/comments-time-machine-links.tsx)? Can you post a screenshot?

**Comment by tooomm** [comment]
I'm sorry... sure!
![Untitled](https://user-images.githubusercontent.com/9874850/65371907-ecdb1100-dc68-11e9-8c90-0373149b3415.png)

**Comment by fregante** [comment]
You probably have some other extension, I'm not seeing that. GitHub's CSS is still:

```css
.markdown-body h1:hover .anchor .octicon-link,
.markdown-body h2:hover .anchor .octicon-link,
.markdown-body h3:hover .anchor .octicon-link,
.markdown-body h4:hover .anchor .octicon-link,
.markdown-body h5:hover .anchor .octicon-link,
.markdown-body h6:hover .anchor .octicon-link {
    visibility: visible;
}
```
