### ISSUE TITLE
Collapse resolved comments

### ISSUE THREAD

**Issue by Mottie** [sindresorhus/refined-github#2515]
## Problem:

Multiple resolved comments take up too much space.

I was just messing around with the following css.

```css
details[data-resolved="true"] + details[data-resolved="true"] {
  margin-top: -3.2em !important;
  transition: margin 300ms;
}
.TimelineItem:hover details[data-resolved="true"] + details[data-resolved="true"] {
  margin-top: 0 !important;
}
```

When you hover over a block of resolved comments, it expands. When you show the resolved content, the comment stays open but the other comments collapse behind it. See the screenshot.

If anyone is interested, please feel free to use it... I don't think it would be a good addition to the `hide-useless-comments` feature. Maybe it could go into a new feature?

## Example URL

https://github.com/sindresorhus/refined-github/pull/2416#pullrequestreview-285236279

## Screenshot

![collapse](https://user-images.githubusercontent.com/136959/68097682-0d100980-fe7e-11e9-83d5-6558954ad02f.gif)
