### ISSUE TITLE
Org switcher moves position when viewed from within an org view

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/refined-github#26]
No better way to explain this other than with a screenshot.

<img width="1680" alt="screen shot 2016-02-19 at 10 17 46" src="https://cloud.githubusercontent.com/assets/885648/13183050/27aca4cc-d6f2-11e5-88c6-b662f10d8288.png">

**Comment by paulmolluzzo** [comment]
This is part of the CSS, so it's the intended look. Relevant CSS:

```css
/* move the dashboard organization switcher to the right column */
.account-switcher {
	position: absolute !important;
	right: 10px !important;
	margin-top: 0 !important;
}
.account-switcher button {
	width: 313px !important;
	z-index: 0 !important;
}
.user-repos {
	position: relative !important;
	top: 50px !important;
}
/* organization dashboard */
.orgpage .pagehead-nav {
	float: left !important;
}
.orgpage .account-switcher {
	right: 0 !important;
}
.orgpage .user-repos {
	position: static !important;
}
#org_your_repos {
	top: 0 !important;
}
```
