### ISSUE TITLE
`display: flex` doesn't play well with Notifications Beta search

### ISSUE THREAD

**Issue by mmarchini** [sindresorhus/refined-github#2703]
Without the extension enabled:

![img-2020-01-14-171320](https://user-images.githubusercontent.com/4048656/72396357-458b5980-36f1-11ea-9e9d-e60a52836b53.png)

With the extension enabled (quick search overlaps the search box):

![img-2020-01-14-171339](https://user-images.githubusercontent.com/4048656/72396365-4cb26780-36f1-11ea-912c-9d0555b5bac6.png)

I looked at the CSS used by refined-github, and it changes the `display` of the search elements from `block` and `inline-block` to `flex`. The autocomplete is a `block` and ends up interacting poorly with other elements there.

I'm using this custom CSS as a workaround:

```css
.js-notifications-container .subnav-search-input {
	display: inline-block;
}

.js-notifications-container .subnav-search {
	display: block;
}
```

but there's probably a better way to do it (using `flex` for the autocomplete, for example).
