### ISSUE TITLE
Draft PR icon looks weird

### ISSUE THREAD

**Issue by Jamesking56** [sindresorhus/refined-github#2755]
The Draft PR icon (changed in #2742) looks really strange and doesn't resemble anything.

![image](https://user-images.githubusercontent.com/253237/73739862-f4461700-473e-11ea-9b4a-6e722db2d717.png)

I'm using Brave Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit) on Ubuntu 18.04 LTS

**Comment by fregante** [comment]
I think you should report that to Brave, it's a plain `filter: drop-shadow()`

**Comment by fregante** [comment]
If you want a quick fix to undo this change, use this CSS:

```css
:root .js-issue-row [aria-label="Open draft pull request"] svg {
	color: #6a737d !important;
	filter: none !important;
}
```

**Comment by jdreesen** [comment]
It looks strange in Firefox, too: 
![image](https://user-images.githubusercontent.com/424602/73743877-d7fea600-474f-11ea-8789-36b9debcab2f.png)

I'm using Firefox 72.0.2 (64-Bit) on Ubuntu 18.04 LTS

**Comment by Jamesking56** [comment]
Would it not be better (and more supported) to use `box-shadow`?

**Comment by fregante** [comment]
`box-shadow` only works on a square, not on the "visible pixels" like `filter`

**Comment by fregante** [comment]
Reopening to discuss alternatives and ask for help to create this SVG:

> [A solid] outline would be best, but there's no way to do that in CSS. I'd have to recreate the icon with the outline and embed the whole new SVG. Anyone wants to take a crack at creating the style in Illustrator/Sketch/etc?

**Comment by Jamesking56** [comment]
Makes more sense to do a solid outline directly in the SVG :+1:

**Comment by FloEdelmann** [comment]
What about this CSS?

```css
.js-issue-row [aria-label='Open draft pull request'] svg {
  stroke: #6a737d; /* GitHub's default draft PR color */
  stroke-width: 2px;
  color: #fff !important;
  paint-order: stroke;
  overflow: visible !important;
}
```

![grafik](https://user-images.githubusercontent.com/202916/73761806-a1d11e80-476f-11ea-8ea3-0fb49d37f90b.png)

**Comment by fregante** [comment]
That's really interesting, if lighter, but there's a small artifact near the arrow that kinds ruins it.

<img src="https://user-images.githubusercontent.com/1402241/74149878-c7fd2f80-4c43-11ea-8853-cf0e110c7f79.png">

**Comment by fregante** [comment]
Actually it's not an artifact, it's just the stroke of the arrow's head touching the arrow's body 😰

**Comment by FloEdelmann** [comment]
We can also make the stroke thinner and use an even darker color instead:

```css
.js-issue-row [aria-label="Open draft pull request"] svg {
    stroke: #24292e;
    stroke-width: 1.2px;
    color: #fff !important;
    paint-order: stroke;
    overflow: visible !important;
}
```

![Screenshot_2020-02-13_15-09-52](https://user-images.githubusercontent.com/202916/74443234-1fcdad80-4e73-11ea-8c9e-115fdba26a69.png)
