### ISSUE TITLE
Stop add scroll bars to quotes blocks

### ISSUE THREAD

**Issue by evandrocoan** [sindresorhus/refined-github#3012]
![image](https://user-images.githubusercontent.com/5332158/79530796-c5a1c200-8046-11ea-960c-53b86f83fe64.png)

> - `url` sets the value returned by `window.location`, `document.URL`, and `document.documentURI`, and affects things like resolution of relative URLs within the document and the same-origin restrictions and referrer used while fetching subresources. It defaults to `"about:blank"`.

```
> - `url` sets the value returned by `window.location`, `document.URL`, and `document.documentURI`, and affects things like resolution of relative URLs within the document and the same-origin restrictions and referrer used while fetching subresources. It defaults to `"about:blank"`.
```

I am already using this CSS from https://github.com/sindresorhus/refined-github/pull/1146#issuecomment-475872046 but it not working for quoted blocks as you can see on the image just above. Only removing `GitHubRedefined` fixes it.
```css
.comment-body blockquote,
.comment-body pre {
  max-height: none !important;
  overflow-y: visible !important;
}
```
