### ISSUE TITLE
`fitTextarea` taking a long time on long PRs

### ISSUE THREAD

**Issue by vjpr** [sindresorhus/refined-github#3031]
![Screen Shot 2020-04-23 at 12 44 32 pm](https://user-images.githubusercontent.com/281413/80090745-450c2580-8560-11ea-8d77-b8f45e90b1e3.png)

Environment is same as: https://github.com/sindresorhus/refined-github/issues/3028#issuecomment-618056096

**Comment by vjpr** [comment]
## Workaround

Disable `fit-textareas` feature.

**Comment by fregante** [comment]
Yes this is an issue with the way the `fit-textarea` module works:

1. Resets height
2. Calculates minimum height
3. Sets height again

This happens for every keystroke.

The alternative way this is generally done is to create a copy of the textarea as a `div`, calculate its height and update the textarea once, only when it changes. 

Side note: GitHub technically has this feature already but it’s limited in height (hardcoded) and doesn’t work as well (it always leaves a 5px extra that causes the scroll bar to appear). Does the native “fit to content” also cause this issue?

**Comment by fregante** [comment]
If you disable `fit-textareas`, you can fix most of GitHub’s native feature with just this CSS:

```css
textarea.js-size-to-fit {
	max-height: none !important; /* Increases the size limit */ 
	box-sizing: content-box; /* Fixes unnecessary scrollbar */
	width: calc(100% - 18px); /* Fixes unnecessary scrollbar */
}
```

However this still leaves 2 issues:
- there's still a height limit (maybe 600px?)
- once the limit is reached, the textarea completely stop resizing

Unfortunately these 2 issues make `fit-textareas` still worth having in Refined GitHub, so it would be great to rewrite https://github.com/fregante/fit-textarea
