### ISSUE TITLE
The commit title input length is now 20px wide

### ISSUE THREAD

**Issue by webknjaz** [sindresorhus/refined-github#3080]
Refined GitHub enabled:
<img width="374" alt="commit-message-incorrect" src="https://user-images.githubusercontent.com/578543/81558475-0531a480-938e-11ea-8c24-af11e7fe20a6.png">

Refined GitHub disabled:
<img width="372" alt="commit-message-correct" src="https://user-images.githubusercontent.com/578543/81558503-17134780-938e-11ea-8fb2-054fe9eaf9b3.png">

This happens when merging PRs https://github.com/aio-libs/aiohttp/pull/4731 and editing individual files https://github.com/scop/aiohttp/edit/changelog-project-url/setup.py?pr=%2Faio-libs%2Faiohttp%2Fpull%2F4731.

Looks like it's because of
```css
.rgh-monospace-textareas #merge_title_field, .rgh-monospace-textareas #commit-summary-input {
    width: calc(72ch + 18px);
    max-width: 100%;
}
```
