### ISSUE TITLE
How to remove the sticky issues top bar?

### ISSUE THREAD

**Issue by evandrocoan** [sindresorhus/refined-github#3086]
1. Open https://github.com/graphql/graphql-js/issues
1. Scroll down on the issues list
1. The top bar is going to sticky

![image](https://user-images.githubusercontent.com/5332158/81759666-b70ac700-949b-11ea-8b6b-fcffe1db26f0.png)

This problem does not happen without Refined-GitHub: (i.e., no sticky toolbar)

![image](https://user-images.githubusercontent.com/5332158/81759759-fafdcc00-949b-11ea-8513-0148a768a853.png)

**Comment by busches** [comment]
https://github.com/sindresorhus/refined-github/blob/e03473b5f08333d00f052578361b78b54d3eab7c/source/features/sticky-discussion-list-toolbar.css is the feature.

The feature is not something you can toggle in the options, but you can turn if off with this custom css.
```css
.Box-header#js-issues-toolbar, 
.Box#js-issues-toolbar > .Box-header {
  position: relative;
}
```
