### ISSUE TITLE
add an option to defaultly hide files section

### ISSUE THREAD

**Issue by HuuLane** [sindresorhus/refined-github#3156]
The first thing I want to see is readme instead of the files section.
![Screenshot_20200530_111534](https://user-images.githubusercontent.com/49306726/83318379-e6288300-a266-11ea-91d1-013a73bb23a0.png)

**Comment by fregante** [comment]
Refined GitHub doesn't have [per-feature options](https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606765382). However you can paste this CSS in the `Custom CSS` field to make it work like you want:

```css
.repository-content.rgh-files-hidden .files {
	display: table;
}
.repository-content:not(.rgh-files-hidden) .files {
	display: none;
}
```

You might also like https://github.com/sindresorhus/hide-files-on-github
