### ISSUE TITLE
Add button to collapse readme/markdown sections

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3224]
Readmes can become link (e.g. https://github.com/sindresorhus/refined-github) so it would be useful sometimes to collapse/expand all sections to sort of generate a temporary "Table of Contents"

<table><th>Open<th>Collapsed

<tr><td width="50%">

![open](https://user-images.githubusercontent.com/1402241/84512846-ded29200-acc8-11ea-9944-e8c94195a63d.png)

<td valign=top>

![collapsed](https://user-images.githubusercontent.com/1402241/84512848-e003bf00-acc8-11ea-81b8-4b2dea1ca00f.png)

</table>

This is especially useful when looking at API documentation like in https://github.com/fregante/text-field-edit

<table><th>Open<th>Collapsed

<tr><td width="50%">

![l](https://user-images.githubusercontent.com/1402241/84513182-602a2480-acc9-11ea-9b1a-ae4dc120eaf1.png)

<td valign=top>

![s](https://user-images.githubusercontent.com/1402241/84513186-615b5180-acc9-11ea-88a6-975941b6309b.png)

</table>

```css
/* demo CSS */
.markdown-body h2 ~ p,
.markdown-body h2 ~ ul,
.markdown-body h2 ~ div,
.markdown-body h2 ~ table,
.markdown-body h2 ~ details {
    display: none;
}
```

I'm thinking that this could be implemented as a "click to toggle" on each heading, plus the usual "alt-click to toggle all". Basically no UI.

Alternatively this could be coupled with a "toggle all" button next to `edit-readme`
