### ISSUE TITLE
Enter a directory / file by clicking its row in the file manager

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/refined-github#3281]
https://github.com/sindresorhus/refined-github

![image](https://user-images.githubusercontent.com/36894700/85688391-ff8be600-b6d1-11ea-8310-eb33535c6212.png)

For now you need to click on the directory name, in this case `.github`. But imagine it's just `a`. It should be possible to enter the directory just by clicking on its row, so it would be more convenient for people who have their mouse DPI set to high value.

**Comment by kidonng** [comment]
```css
.js-navigation-open {
  display: inline-block;
  width: 100%;
}
```
