### ISSUE TITLE
pin/unpin issue button layout broken

### ISSUE THREAD

**Issue by miyataka** [sindresorhus/refined-github#3298]
> 2. Include a full URL where the bug appears.

https://github.com/miyataka/fcmpush/issues/12
or
some your own issue URL.

> 3. Include a screenshot/gif 

- when disabled refined-github
![image](https://user-images.githubusercontent.com/15692588/85944624-2caaf380-b973-11ea-8ebb-13d6a50cc5d3.png)

- when enabled refined-github
  - some error occuered 
![image](https://user-images.githubusercontent.com/15692588/85944645-6f6ccb80-b973-11ea-9cdc-4dcbd1fc626f.png)
  - and here layout is broken
![image](https://user-images.githubusercontent.com/15692588/85944667-94f9d500-b973-11ea-94bf-6869f8c7229a.png)

**Comment by miyataka** [comment]
some version info
![image](https://user-images.githubusercontent.com/15692588/85944815-9a0b5400-b974-11ea-9859-bd96808a8cfd.png)
![image](https://user-images.githubusercontent.com/15692588/85944834-b1e2d800-b974-11ea-9cca-5f94d0f68514.png)

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/blob/7500dc7ae236a21b26086ae163c45f32dbca83a9/source/features/clean-pinned-issues.css#L43-L46

**Comment by fregante** [comment]
The selector needs to be made more specific

**Comment by kidonng** [comment]
Plus this:

![image](https://user-images.githubusercontent.com/44045911/85970421-05990400-b9fd-11ea-854f-3ad5df9660b2.png)

**Comment by fregante** [comment]
> Culprit:

That's the base of the feature, it can't be changed. Are there any floats that are pushing that down? Maybe the title just needs a `max-width`

**Comment by kidonng** [comment]
> Are there any floats that are pushing that down

You are right:
![image](https://user-images.githubusercontent.com/44045911/86257471-2b383000-bbec-11ea-9566-8271a25b4849.png)

So basically change:

```css
[action$='unpin'] svg {
		margin-left: -10px;
		margin-right: 10px !important;
	}
```

to:

```css
.pinned-issue-item form button {
  float: unset !important;
  margin-left: -5px;
  margin-right: 2px !important;
}
```
