### ISSUE TITLE
Hide "Readme" text from repositories

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3580]
Does anyone have any idea of why this link exists on repo roots like https://github.com/sindresorhus/refined-github?

<img width="201" alt="" src="https://user-images.githubusercontent.com/1402241/93687042-48103100-fa80-11ea-93fd-d589b00b261a.png">

It points to the same page. Should we hide it? It can just be part of `refined-github.css`:

```css
.BorderGrid-cell [href="#readme"] {
	display: none;
}
```
