### ISSUE TITLE
On milestones page, the bulk issue-update toolbar has incorrect padding that breaks vertical centering

### ISSUE THREAD

**Issue by jonboiser** [sindresorhus/refined-github#3606]
Here's an example of this kind of page https://github.com/learningequality/kolibri/milestone/60.

![image](https://user-images.githubusercontent.com/10248067/94746436-8e437b00-0331-11eb-8fb8-a19c19ca352d.png)

If you click any checkbox, the menu a the top right of this div will change the bulk-update menu, and as you can see in the screenshot, the menu of dropdowns is missing some padding.

I tried to fix this by adding this custom CSS (copying the selector from the DOM inspector)

```css
#js-issues-toolbar > div.table-list-triage.js-issues-toolbar-triage > div {
	padding: 13px;
}
```

But this messes with the same menu on the main issues page:

Next screenshot is from https://github.com/learningequality/kolibri/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc (click any checkbox to see this; without the above custom CSS, you won't see this excessive padding).

![image](https://user-images.githubusercontent.com/10248067/94746754-42dd9c80-0332-11eb-960b-945dde05dec0.png)

So I added a second rule to override the first one

```css
#js-issues-toolbar > div.table-list-triage.flex-auto.js-issues-toolbar-triage > div {
	padding: 0 !important;
}
```

And this combination of custom CSS seems to fix the layout issues for me.
