### ISSUE TITLE
Adjust `show-whitespace` color so it also works in dark mode

### ISSUE THREAD

**Issue by Shinigami92** [sindresorhus/refined-github#3772]
https://github.com/sindresorhus/refined-github/blob/master/source/features/show-whitespace.css

![image](https://user-images.githubusercontent.com/7195563/100459371-aa5f6080-30c5-11eb-9b69-db203b350ae6.png)

As you can see I'm using the [GitHub-Dark Theme](https://github.com/StylishThemes/GitHub-Dark) but the whitespace are not really visible with this theam :slightly_frowning_face:  
When I look into the source code, I can see a hard-coded `fill`. Can we make this configurable or overridable in any way?
I tried to just override it in Chrome via DevTools, but I had no luck :thinking: 
Don't know what I'm doing wrong or if this is even the correct color setting

**Comment by sindresorhus** [comment]
GitHub will soon support Dark Mode natively and we can fix it properly then.

**Comment by Shinigami92** [comment]
Interesting, didn't know that GitHub will support Dark Mode anytime soon.
Do you have a source for a roadmap or whatsoever?

So should we close this for now? Or let it open to track that we want to support it when native Dark Mode comes out?

**Comment by fregante** [comment]
Unfortunately background images can't be updated dynamically. You have 2 options to paste in the CSS field:

```css
[data-rgh-whitespace] {
    filter: brightness(20);
}
```

or

```css
[data-rgh-whitespace="tab"] {
    background-image: url(data:image/svg+xml,%3Csvg preserveAspectRatio=\"xMinYMid meet\" viewBox=\"0 0 12 24\" xmlns=\"http://www.w3.org/2000/svg\"%3E%3Cpath d=\"M9.5 10.44L6.62 8.12L7.32 7.26L12.04 11V11.44L7.28 14.9L6.62 13.9L9.48 11.78H0V10.44H9.5Z\" fill=\"white\"/%3E%3C/svg%3E);
]
[data-rgh-whitespace="space"] {
    background-image: url(data:image/svg+xml,%3Csvg preserveAspectRatio=\"xMinYMid meet\" viewBox=\"0 0 12 24\" xmlns=\"http://www.w3.org/2000/svg\"%3E%3Cpath d=\"M4.5 11C4.5 10.1716 5.17157 9.5 6 9.5C6.82843 9.5 7.5 10.1716 7.5 11C7.5 11.8284 6.82843 12.5 6 12.5C5.17157 12.5 4.5 11.8284 4.5 11Z\" fill=\"white\"/%3E%3C/svg%3E);
}
```

**Comment by Shinigami92** [comment]
A value of `4` works great :+1: 

```css
[data-rgh-whitespace] {
    filter: brightness(4);
}
```

I will suggest this to the theme repo

**Comment by silverwind** [comment]
I'd generally suggest replacing those images with proper SVGs that can be targeted via CSS.

**Comment by Shinigami92** [comment]
Ok good too know.
I'm not really into CSS and more a user of frameworks like Vuetify ^^
And this handles all the stuff for me

**Comment by fregante** [comment]
@silverwind I knew you would suggest that, but SVGs don’t have `background-repeat`, plus they’re part of the content, but the content here should be just a tab character.

**Comment by silverwind** [comment]
Hmm I see, I guess background is justified in such a case. I think it may be possible to `fill: var(--somevar)` to make the color changeable in CSS, but I'm not 100% sure on browser support of that.

**Comment by fregante** [comment]
No, backgrounds and `<img>` don’t have access to anything on the page, including the variables

**Comment by silverwind** [comment]
Looks like it's possible using a `mask-image` trick:

https://jsfiddle.net/silverwind/Lpr736t9/

Thought an even better solution would be to use a color in the middle of the lightness spectrum which will work on both light and dark background, e.g. `#80808080`.

**Comment by fregante** [comment]
> mask-image

I'm gonna assume that masks will be more _expensive_ than just drawing the SVG and considering that this will be used by hundreds of elements that's gonna be a performance hit for no good reason.



> middle of the lightness spectrum which will work on both light and dark background

That's a good solution, as long as it actually looks good on both. `#80808040` is a little too light for example



> having it configurable never bad to have.

Given the 190 features we have, [configurability is bad.](https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606765658)

**Comment by silverwind** [comment]
> Given the 190 features we have, configurability is bad.

I didn't mean user-configurable, but outside-configurable via CSS 😉

**Comment by fregante** [comment]
This is already outside-configurable: https://github.com/sindresorhus/refined-github/issues/3772#issuecomment-735004772 😁

**Comment by silverwind** [comment]
Yeah, that's what we do currently and it's ugly.

Anyways, if you could choose a color that works on dark and light, that'd be my preference and you don't even need to change it once GH enabled their dark mode.

**Comment by fregante** [comment]
> if you could choose a color that works on dark and light

PR welcome for such a color, as previously said:

> That's a good solution, as long as it actually looks good on both. #80808040 is a little too light for example

**Comment by Shinigami92** [comment]
Dark mode arrived 🎉 

<img src="https://user-images.githubusercontent.com/7195563/101522115-1627b000-3987-11eb-9c5d-fa97c2c17604.png" width="300px"/>

**Comment by fregante** [comment]
Great! Does GitHub make it easy to detect dark mode? Because an alternative solution, if the color can’t be found, would be to just use the detection and use a new rule.

**Comment by silverwind** [comment]
There is `data-color-mode` on `<html>` but I'd suggest refraining from detection for this feature if possible.

**Comment by mcornella** [comment]
So I noticed that the current color is very close to the line numbers, so I looked at how their color changes from light to dark mode. The color uses the [`--color-diff-blob-num-text` CSS variable](https://primer.style/primitives/), which is

<table>
<tr>
  <td>Mode
  <td>HSL
<tr>
  <td>Light
  <td>hsl(210deg 13% 12% / 30%)
<tr>
  <td>Dark
  <td>hsl(210deg 67% 96% / 30%)
</table>

The current svg fill color is `rgba(36,41,46,25%)`, which is `hsl(210deg 12% 16% / 25%)`. More or less the same as in light mode, so to bring it up to the same color in Dark mode I multiply the saturation by `67/12` and brightness by `96/16`, so the CSS would look like this:
```css
:root[data-color-mode="dark"] [data-rgh-whitespace] {
	filter: saturate(5.5) brightness(6);
}
```
I also tried with `filter: invert(1)` and it kinda looks the same without so much math. Preview:
![image](https://user-images.githubusercontent.com/1441704/102016784-e8fe4780-3d62-11eb-9ea5-da4973d23c42.png)
![image](https://user-images.githubusercontent.com/1441704/102016795-0501e900-3d63-11eb-8c24-5c505e1ac778.png)

This works but as @silverwind said, it doesn't support GitHub Dark. But it looks like they already support RGH:
![image](https://user-images.githubusercontent.com/1441704/102016933-d9333300-3d63-11eb-9f45-01def7d7c15a.png)
So we might not need to do anything else in that regard.
