### ISSUE TITLE
Support for Github Darkmode

### ISSUE THREAD

**Issue by fionera** [sindresorhus/refined-github#3798]
When using Refined Github with the new Github Darkmode the Activity List is rendered with a white background.

https://imgur.com/a/uy8K50q

**Comment by kubukoz** [comment]
Also, this:

![image](https://user-images.githubusercontent.com/894884/101520485-dcee4080-3984-11eb-97c5-e0997dffa513.png)

**Comment by yakov116** [comment]
OH MY OMG OMG. So cool

@fregante this is going to be real fun.....

**Comment by mcornella** [comment]
This custom CSS makes it work in both light and dark mode:
```css
.dashboard .js-all-activity-header + div {
    background-color: var(--color-bg-canvas);
    border-color: var(--color-border-primary);
}
```
Go to the extension settings to apply that.

**Comment by jonrohan** [comment]
The best way to go is to use the CSS variables GitHub is now using, here's a list.

https://primer.style/primitives/

**Comment by kamal** [comment]
Also this 
![image](https://user-images.githubusercontent.com/269/101529578-99281680-3945-11eb-841d-99744d4009fb.png)

**Comment by busches** [comment]
> The best way to go is to use the CSS variables GitHub is now using, here's a list.
> 
> https://primer.style/primitives/

Best way shouldn't break every enterprise user out there.

**Comment by fregante** [comment]
@busches `var(--property, fallback)`

**Comment by mcornella** [comment]
Would this work?
```css
.dashboard .js-all-activity-header + div {
    background-color: var(--color-bg-canvas, #fff);
    border-color: var(--color-border-primary, var(--github-border-color));
}
```

**Comment by mcornella** [comment]
[Also this for the reaction border colors](https://github.com/sindresorhus/refined-github/issues/3798#issuecomment-740790219):
```css
button.reaction-summary-item {
	border-top-color: var(--color-border-primary, rgb(225, 228, 232));
    border-bottom-color: var(--color-border-primary, rgb(225, 228, 232));
}
```
