### ISSUE TITLE
Let users disable `clean-dashboard`

### ISSUE THREAD

**Issue by smac89** [sindresorhus/refined-github#3816]
I'm talking about the homepage: https://github.com/

I prefer the original GitHub homepage activities section over what this plugin does. Is there an easy way to toggle it off? I've searched through the options and haven't found anything.

I have tried using these CSS rules to disable some of the work done in this area, but I wish there was a global CSS rule I can toggle to disable all modifications done in that section.

```css
:root > * {
  --github-border-color: var(--color-border-primary);
}

.dashboard .flex-items-baseline .f6.mt-2 {
}

/* leave the box, I like it */
.dashboard .js-all-activity-header + div .Box {
}

/* Remove the top border */
.dashboard-rollup-items .body {
}

/* Remove the border between collapsible items */
.dashboard .body > .border-bottom {
}

.dashboard .flex-items-baseline.py-3 {
}
```

It just feels too condensed for my liking, and I prefer the way GitHub spaces all the items out.
