### ISSUE TITLE
Transform repository navigation to a simple `overflow-y: scroll`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4286]
Instead of items disappearing in `more-dropdown`, I'd rather be able to scroll the nav bar horizontally natively:

![gif](https://user-images.githubusercontent.com/1402241/116358052-69f84000-a827-11eb-89b8-2e02ee9043d3.gif)

I'd do away with the dropdown completely, extracting all the items back out instead of hiding them like `more-dropdown` does.

Unfortunately I don’t think this change would be welcome for users who don't have a horizontal scrolling mousewheel/trackpad, and I know Sindre doesn't like showing all the items on the bar, so this issue is just for tracking/discussion.

**Comment by fregante** [comment]
This can currently be achieved by disabling `more-dropdown` + this CSS:

```css
.js-responsive-underlinenav {
	padding-right: 0 !important;
}
.js-responsive-underlinenav-item {
	visibility: visible !important;
}
.UnderlineNav-actions  {
	display: none;
}
.UnderlineNav-body {
	overflow-y: scroll;
}
.UnderlineNav-body::-webkit-scrollbar {
	height: 0;
	width: 0;
}
```

**Comment by sindresorhus** [comment]
I'm -0 about this. I don't like it, but I also don't feel strongly about it.

**Comment by kidonng** [comment]
If I remember correctly, that's how GitHub used to do on mobile web page. Now that they choose to use a dropdown, I think we should stick to it.

**Comment by fregante** [comment]
While I'm at it, here's a related "refinement" that won't be part of Refined GiHub 😃 

<img width="539" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/116839634-4e14e580-abfd-11eb-9ec7-e1f3c1f187ae.png">


```css
.UnderlineNav-octicon {
	margin-right: 0 !important;
}
.UnderlineNav-item [data-content] {
	display: none;
}
```
