### ISSUE TITLE
`pr-approvals-count` should hide the duplicate tooltip

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4371]
URL: https://github.com/sindresorhus/refined-github/pulls

<img width="149" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/118632504-af8ea400-b7fa-11eb-82d2-0aa8fc64cb3d.png">

The feature already shows the tooltip inline. We should disable it. Something like:

```css
the right selector:is(:before, :after) {
	content: none;
}
```
