### ISSUE TITLE
Main news feed seems to have changed layout

### ISSUE THREAD

**Issue by MostHated** [sindresorhus/refined-github#4380]
For as long as I can remember, the news feed has looked like this:
<details>
 <summary>Expected news feed</summary>

![](https://i.imgur.com/EfXpbhn.png)

</details>

but as of yesterday or the day before, it has looked like this:
<details>
 <summary>Current news feed</summary>

![](https://i.imgur.com/KDJ14MB.png)

</details>

Did something change recently in which I need to make an adjustment on my side to get that back? I definitely prefer the prior news feed.

**Comment by yakov116** [comment]
Did you disable any features? Looks like `hide-useless-newsfeed-events`  is not enabled.

**Comment by MostHated** [comment]
I have not made any changes to it in several months. The last changes that were made was custom this custom CSS which I was advised to use in a previous ticket:

```css
/* #1864 restore Star/Unstar buttons in dashboard */
.dashboard .flex-items-baseline [value='Star'],
.dashboard .flex-items-baseline [value='Unstar'] {
	display: block !important;
}
.dashboard .watch_started .border-gray.flex-items-baseline .text-bold.text-gray-dark  {
	display: block !important;
}
```
