### ISSUE TITLE
New github reaction style makes `reactions-avatars` look weird 

### ISSUE THREAD

**Issue by ShadowJonathan** [sindresorhus/refined-github#4674]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

Github is (presumably) doing an A/B Reaction style test right now, I got in, and refined-github is messing with the reaction style.

### Screenshot

![image](https://user-images.githubusercontent.com/22740616/129766372-3b2a2cda-bf3d-4800-9705-7818e65cd06d.png)
(with refined-github)

![image](https://user-images.githubusercontent.com/22740616/129766437-6b90596b-6775-4e65-a212-5f61fd625c28.png)
(without)

### Example URL

https://github.com/vector-im/element-web/issues/18248

### Browser(s) used

Microsoft Edge (chromium) 92.0.902.73

**Comment by fregante** [comment]
**@refinedgithubbers** Should we disable this feature via hotfix for now?

**Comment by yakov116** [comment]
I don't see anything wrong _(yet)_

**Comment by fregante** [comment]
This can be somewhat fixed by adding this to the custom CSS field:
```css
/* https://github.com/sindresorhus/refined-github/issues/4674 */
.reaction-summary-item:not(.js-reaction-group-button) span:first-of-type {
	all: unset;
	margin: 0 1.2em 0 0.5em;
}
```

**Comment by ShadowJonathan** [comment]
FWIW this A/B test does not occur when you're not logged in.

**Comment by yakov116** [comment]
Now I do, do a hotfix (Since now its broken for me and I am selfish).

This will require some careful thinking for GHE

**Comment by fregante** [comment]
Some style is still leaking since it's not bound to any `rgh-` classes. Any fix should probably just add a `rgh-reactions-avatar` class to each button and target that in every selector.

Also discussed in https://github.com/sindresorhus/refined-github/pull/4635#issuecomment-891278999

**Comment by kidonng** [comment]
Mea culpa, I could have submitted a better fix in #4635 to prevent this.

Meanwhile leaked styles can be temporarily solved with:

```css
.reaction-summary-item:not(.js-reaction-group-button) span:first-of-type {
    all: unset;
    /* From GitHub */
    margin-left: 2px;
    padding: 0 4px;
}
```
