### ISSUE TITLE
Make 'Expand PR merge status' as a feature - so it can be turned off

### ISSUE THREAD

**Issue by xnuk** [sindresorhus/refined-github#4809]
### Description

https://github.com/sindresorhus/refined-github/blob/99e81baaac8c787d1a59b74194c9437e9c29ffdf/source/refined-github.css#L73-L76

Some PRs have a bunch of required tests in order to merge - let's say, 106 tests - and that's a lot of scroll to writing a new comment, clicking "Hide all checks" every time makes me little annoying. In this case, I do not prefer expanding all of these. But some people would like this, so it would be good if it's able to turn off and on. Or something like `max-height: 999px;`?

### Screenshot

![GitHub PR check statuses showing 105 expected and 1 successful checks](https://user-images.githubusercontent.com/3071003/134493588-42d55ce7-9822-40b6-9070-3822f35455c6.png)

I got this in https://github.com/swc-project/swc PRs.

### Example URL

https://github.com/swc-project/swc/pulls?q=is%3Apr+is%3Aopen+-is%3Adraft

**Comment by xnuk** [comment]
For someone like me: Add this into **Custom CSS** setting:

```css
:root .branch-action-item.open:not(.branch-action-item-simple) > .merge-status-list.merge-status-list {
	max-height: 231px;
}
```
