### ISSUE TITLE
Doesn't show list of repositories contributed to

### ISSUE THREAD

**Issue by fnky** [sindresorhus/refined-github#524]
The extension hides the **Repositories you contribute to** list in the sidebar of the GitHub front page. It also hides the (convenient) header from the **Your repositories** list with the **New repository** button.

![image](https://user-images.githubusercontent.com/995050/27484604-23535a14-582a-11e7-9fe3-6420ff52dd00.png)

**Comment by bfred-it** [comment]
That's a feature: 

https://github.com/sindresorhus/refined-github/blob/2ba0840b852bebfc881b8bf50db7182287047a70/extension/content.css#L15-L18

Use Stylish to undo that feature with:


```css
.dashboard-sidebar > .boxed-group[role="navigation"]:not(.repos) {
	display: block !important;
}
```
