### ISSUE TITLE
Make hiding of events in dashboard configurable

### ISSUE THREAD

**Issue by xPaw** [sindresorhus/refined-github#561]
This extension hides pushes for example, and I would like to keep seeing them.

**Comment by bfred-it** [comment]
You can use [Stylish](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en) to display them again:

```css
.news .alert.push {
    display: block !important;
}
```
