### ISSUE TITLE
Don't hide new comment toolbar

### ISSUE THREAD

**Issue by Soreine** [sindresorhus/refined-github#566]
<img width="724" alt="screen shot 2017-07-04 at 11 16 18" src="https://user-images.githubusercontent.com/5644953/27823791-aaa55354-60aa-11e7-8b01-01817183db2f.png">

This is an anti-feature. It does not remove UI bloat. Instead it removes the ability to easily quote an entire block of text, to easily convert a few lines in an ordered list, etc.
The toolbar is not just about typing Markdown. It has editing capabilities.

Since you're against adding options, I suggest to just remove that feature.

**Comment by bfred-it** [comment]
You can use [Stylish](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en) to display them again:

```css
.toolbar-group .toolbar-item {
    display: block !important;
}
```

**Comment by Soreine** [comment]
Thank you for the workaround.

Here is the exact CSS rule:
```css
@-moz-document regexp("^https?://((gist|guides|help|raw|status|developer)\\.)?github.com((?!generated_pages/preview).)*$"), domain("githubusercontent.com") {
    .toolbar-group .toolbar-item {
       display: block !important;
    }
    .toolbar-group {
       display: inline-block !important;
    }
```

The first line restrict the style to GitHub.com only. It was written for Firefox since I'm using the unofficial Firefox version of Refined GitHub. You can either adapt it or remove it if you are using Chrome.

<img width="728" alt="screen shot 2017-07-04 at 12 32 18" src="https://user-images.githubusercontent.com/5644953/27826814-d9210368-60b4-11e7-8274-c46c8528036f.png">

--- 

My suggestion still hold though. Maybe some people will agree.
