### ISSUE TITLE
Versioning, deployment improvements

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#595]
I'll preface by saying that the current setup (deploy every push to master) works well for me and I **prefer it** over manually creating tags/releases.

I do however have two wishes:

- [x] limit to one release per day
- [ ] shorter version numbers (`17.7.8` instead of `17.7.8.1317`)

Travis recently added a daily cronjob feature which we could use to implement daily deployment, but [it runs regardless of changes](https://github.com/travis-ci/beta-features/issues/1#issuecomment-285280591).

These changes are possible but we need two pieces:

- something that stops Travis as soon as it sees no new commits **since the last build** (which might not be exactly 24 hours before)
- something that stores the previous version in Travis' cache ([seems possible](https://docs.travis-ci.com/user/caching/#Arbitrary-directories)) as `y.m.d` and automatically bumps it to `y.m.d.1` if multiple builds happen in the same day

Ideas? Have you seen such packages? Know how to do this?

**Comment by sindresorhus** [comment]
@bfred-it I think we should just go with the daily cronjob right now and we can figure out how to only release when there are new commits later on.

**Comment by jgierer12** [comment]
How about using a dedicated CD service (Jenkins/Heroku pipelines etc)? I don't think Travis is the right tool for such a relatively complex deployment scenario

**Comment by bfred-it** [comment]
I never used Jenkins, but if it's easier to manage I wouldn't be opposed to it.

**Comment by sindresorhus** [comment]
I would prefer to use a hosted service unless we really can't. I hate doing DevOps and we have better things to spend our time on than manage a Jenkins instance.

**Comment by busches** [comment]
What's the aversion to multi deploys a day? The current solution works and the proposed solutions all appear to overcomplicate the release process.

**Comment by bfred-it** [comment]
The problem is that we can't even make readme changes that they're deployed instantly. Or you can't merge something and then make some additional changes before deploy.

 I mean no big deal, just a bit annoying. 

Deploying once a day was pretty easy really, the 3-point version is a little less easy.

**Comment by bfred-it** [comment]
This is the code needed to cache, retrieve and bump the version:

```yml
cache:
  directories:
  - $HOME/.version-store
script:
  # 17.7.12 (first deploy of the day)
  # 17.7.12.1025 (successive deploys)
  - CURR=$(date -u +%y.%-m.%-d)
  - PREV=$(cat $HOME/.version-store/v || true) 
  - if [[ $PREV" =~ "^$CURR ]]; then CURR=$(date -u +%y.%-m.%-d.%-H%M); fi;
  - echo $CURR > $HOME/.version-store/v
```

See tests here: https://travis-ci.org/bfred-it/sandbox/builds/252651771

Except this script can't live in `.travis.yml` because `deployment` only accepts one command, so I'll have to transpose it to package.json or a `.sh` file.
