### ISSUE TITLE
Incorrect spacing in diff

### ISSUE THREAD

**Issue by jgierer12** [sindresorhus/refined-github#601]
>My commit adds a single line without any preceeding whitespace, but it get's displayed with a small extra indentation (which is confusing).
>
>Correct: (plain github)
![screenshot from 2017-07-09 18-45-49](https://user-images.githubusercontent.com/2073458/27995940-6aef495a-64d7-11e7-846c-3cd88d64d6bf.png)
>
>Wrong: (refined github enabled)
![screenshot from 2017-07-09 18-45-15](https://user-images.githubusercontent.com/2073458/27995941-6db3f398-64d7-11e7-93d8-1755fc8315cc.png)
>
>The Raw commit is here: https://github.com/dunst-project/dunst/commit/717c747a8caf0f823da0e4e45bbb632ef46c68ee

*@bebehei in https://github.com/sindresorhus/refined-github/issues/590#issuecomment-313931801*

**Comment by jgierer12** [comment]
I've been able to prevent this with a few CSS modifications:

```css
.blob-code-inner {
  white-space: nowrap;
  padding-left: 1em;
}

.blob-code-addition::before, .blob-code-deletion::before {
  position: absolute;
  top: 1em;
  left: 1em;
}
```

Disclaimer: Only tested via Firefox devtools and only on https://github.com/dunst-project/dunst/commit/717c747a8caf0f823da0e4e45bbb632ef46c68ee
