### ISSUE TITLE
There is no command line instruction in Pull request page.

### ISSUE THREAD

**Issue by Nozibulla** [sindresorhus/refined-github#610]
Before using refined-github: https://dl.dropboxusercontent.com/1/view/5pdqt484sq5b9hl/Apps/Shutter/Selection_001.jpg

After using refined-github: https://dl.dropboxusercontent.com/1/view/c6bsia2n52szdiz/Apps/Shutter/Selection_002.jpg

**Comment by bfred-it** [comment]
This extension is for pro-users (who don't need instructions) so I understand the change, but now that you showed me that I undid this change with Stylish:

```css
.alt-merge-options {
	display: inline-block !important;
}
```
