### ISSUE TITLE
Restore Broadcasts

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#637]
<img width="319" alt="screen shot 2017-07-19 at 17 36 12" src="https://user-images.githubusercontent.com/1402241/28360685-c928561e-6ca8-11e7-8fac-8e0a8ce61a34.png">

I think updates from GitHub are useful, in fact we could even use their own code to highlight our own recent big changes and features (and implemented as a reusable package)

<img width="320" alt="screen shot 2017-07-19 at 17 41 23" src="https://user-images.githubusercontent.com/1402241/28360936-96072408-6ca9-11e7-8264-f1b2bc88fa6e.png">

**Comment by bfred-it** [comment]
In the meantime, Stylish fix:


```css
.dashboard-sidebar .octofication {
  display:block !important;
}
```
