### ISSUE TITLE
Allow labels to be placed the original way

### ISSUE THREAD

**Issue by onury** [sindresorhus/refined-github#849]
I like most features but moving labels to a third line makes the list too long and the right part is a huge negative space. IMO, It'd be better to make this optional.

**Comment by bfred-it** [comment]
I don't see adding an option for this; You can undo it with Stylish:

```css
// Undo https://github.com/sindresorhus/refined-github/blob/bbf456b08dc8ef89a2cfbec71df65a4cb0d6a71f/source/content.css#L594-L601
.js-issue-row .lh-condensed {
    display: block !important;
}
```
