### ISSUE TITLE
Add ability to view and link to Markdown source

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#946]
There's no way to view the source of Markdown files inside the GitHub UI. All you can do is click "Raw" to view the raw file.

A trick I discovered is to click "Blame". Then you can view the source of Markdown and even link to specific lines.

Would be nice to add a "Source" button when viewing a rendered Markdown file, which would go to the blame view, but add a query param that instructs Refined GitHub to tweak the UI, like removing the blame components, so it's a clean source view.

---

*For anyone that wants this, please also send this feature request to GitHub: support@github.com*

**Comment by bfred-it** [comment]
Related: https://github.com/isaacs/github/issues/297

**Comment by bfred-it** [comment]
Usable userstyle (click the import button) for `blame` urls ending with `?blame=hide`:

```css
@-moz-document regexp("https:\\/\\/github.com\\/.*\\/.*\\/blame\\/.*\\?blame=hide") {
	.blame-commit,
	.blob-reblame {
		display: none
	}
	.blame-hunk {
		border-bottom: 0 !important
	}
}
```
